######################################################################
# Add config info here!
# To add a new documentation topic of name DOC_TOPIC, extend both 'collections' and 'header_pages' with the following
#
#collections:
# [current collections info]
# DOC_TOPIC:
#  output:true
#
#header_pages:
# [current header_pages info]
# - DOC_TOPIC.md
#

collections:
 documentation:
  output: true
 gazebo-simulation:
  output: true
 gaze-tracking:
  output: true
 SIM:
  output: true
 mobility-unlimited:
  output: true
 roomba:
  output: true
 autochair:
  output: true
 openpose:
  output: true

header_pages:
 - documentation.md
 - gazebo-simulation.md
 - gaze-tracking.md
 - SIM.md
 - mobility-unlimited.md
 - roomba.md
 - autochair.md
 - openpose.md


######################################################################
# Nothing below here should normally be messed with
######################################################################

theme: minima

plugins:
 - jekyll-relative-links
 - jekyll-feed
 - premonition


relative_links:
 enableD: true
 collections: true

baseurl: /RnD
